# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65f5dd42ee365b45a05d40eb4961e789e6e9c33c2083a3c657c5e1cddffffc3974cf8c402b05e07be33b63bfea7337862ea055ea6367b23ede97c7131a7fd427

test:
  secret_key_base: d74de5ba0864cd85338abcb85fe3eea9af349b6d53e846f8d6a872663e729d19b8c1cc138a6c77525b5ecff64ed6cf57ed38cc6a4e7b55bd706b52d153beb9be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
